keycloak:
  realm: your-realm
  auth-server-url: http://localhost:8080/auth
  resource: your-client-id
  credentials:
    secret: your-client-secret
  use-resource-role-mappings: true
  principal-attribute: preferred_username

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/your-realm
        registration:
          keycloak:
            client-id: your-client-id
            client-secret: your-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
