spring.application.name=backend
# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db_name
spring.datasource.username=db_username
spring.datasource.password=db_password

# Hibernate properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update


keycloak.realm=projettransformation
keycloak.auth-server-url=http://localhost:8080/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fadmin%2Fmaster%2Fconsole%2F&state=72ea47ba-d03a-4826-96c8-2950599ea43b&response_mode=query&response_type=code&scope=openid&nonce=75cf9657-b49d-43c2-85cc-ea20218c96d3&code_challenge=84HF_ykqUfGEwU0AU31W-4PSF076ZSjvFuC_Qz8E3pc&code_challenge_method=S256
keycloak.resource=admin
keycloak.credentials.secret=fD$@%54X5-c%Sm
keycloak.use-resource-role-mappings=true

